<a href="https://colab.research.google.com/github/tofighi/Linear-Algebra/blob/main/M02_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Differences in Matrix Representation - SymPy vs. NumPy
SymPy stores entries in 1D arrays, while NumPy stores entries in 2D arrays.

In [ ]:
import sympy as sp 
import numpy as np
sp.init_printing(use_unicode=True)

In [ ]:
#Sympy version of our demo matrix
As = sp.Matrix([[1,2,3], [4,5,6]])
As

⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

In [ ]:
#Numpy version of our demo matrix - Libraries are inter-compatible
An = np. array(As)
An

array([[1, 2, 3],
       [4, 5, 6]], dtype=object)

In [ ]:
#We can't obtain the dimensions of the SymPy Matrix easily
len(As)

In [ ]:
#We can obtain the size of the NumPy Matrix:
size= [len(An), len(An[0])]
size

In [ ]:
#We can also obtain the size of the NumPy Matrix using shape property
An.shape

In [ ]:
An

array([[1, 2, 3],
       [4, 5, 6]], dtype=object)

In [ ]:
An+1

array([[2, 3, 4],
       [5, 6, 7]], dtype=object)

In [ ]:
As.T

⎡1  4⎤
⎢    ⎥
⎢2  5⎥
⎢    ⎥
⎣3  6⎦

In [ ]:
An.T

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=object)

In [ ]:
3*As

⎡3   6   9 ⎤
⎢          ⎥
⎣12  15  18⎦

In [ ]:
As/2

⎡1/2   1   3/2⎤
⎢             ⎥
⎣ 2   5/2   3 ⎦

In [ ]:
Bs = 3*As
Bs

⎡3   6   9 ⎤
⎢          ⎥
⎣12  15  18⎦

In [ ]:
#As is 2x3 Bs^T is 3x2, so the product is 2x2 ...
As*Bs.T

⎡42  96 ⎤
⎢       ⎥
⎣96  231⎦

In [ ]:
#Try the following code, it will generate ShapeError: Matrix size mismatch: (2, 3) * (2, 3).
#As*Bs

In [ ]:
# You can use Numpy library as well
Bn = 3*An
Bn

array([[3, 6, 9],
       [12, 15, 18]], dtype=object)

In [ ]:
# we use dot method in Numpy for Matrix multiplications
np.dot(An, Bn. T)

array([[42, 96],
       [96, 231]], dtype=object)

In [ ]:
# if you use * for multiplication in Numpy, it is element-wise, it is NOT a matrix product
An*Bn

array([[3, 12, 27],
       [48, 75, 108]], dtype=object)

# Matrix Inverse

In [ ]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x) 
print (y) 
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
